export const DefaultPermissions = [
	{ permissionName: 'Dashboard', sortId: 1 },
	{ permissionName: 'Employee Cost', sortId: 2 },
	{ permissionName: 'Cost Allocations', sortId: 3 },
	{ permissionName: 'Journals Entries', sortId: 4 },
	{ permissionName: 'TimeLogs', sortId: 5 },
	{ permissionName: 'TimeSheets', sortId: 6 },
	{ permissionName: 'Roles', sortId: 7 },
	{ permissionName: 'Users', sortId: 8 },
	{ permissionName: 'Integrations', sortId: 9 },
	{ permissionName: 'Configurations', sortId: 10 },
	{ permissionName: 'Subscriptions', sortId: 11 },
	{ permissionName: 'Custom Rules', sortId: 12 },
	{ permissionName: 'Time Summary', sortId: 13 },
	{ permissionName: 'Payroll Summary', sortId: 14 },
	{ permissionName: 'Customer Overview', sortId: 15 },
];

export const DefaultAdminPermissions = [
	{
		permissionName: 'Dashboard',
		sortId: 1,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Employee Cost',
		sortId: 2,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Cost Allocations',
		sortId: 3,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Journals Entries',
		sortId: 4,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'TimeLogs',
		sortId: 5,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'TimeSheets',
		sortId: 6,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Roles',
		sortId: 7,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Users',
		sortId: 8,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Integrations',
		sortId: 9,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Configurations',
		sortId: 10,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Subscriptions',
		sortId: 11,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Custom Rules',
		sortId: 12,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Time Summary',
		sortId: 13,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Payroll Summary',
		sortId: 14,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		permissionName: 'Customer Overview',
		sortId: 15,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
];
